//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  general: General;
  generalConnection: GeneralConnection;
  acts: Acts;
  actsConnection: ActsConnection;
  journal: Journal;
  journalConnection: JournalConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGeneralArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGeneralConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GeneralFilter>;
};


export type QueryActsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryActsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ActsFilter>;
};


export type QueryJournalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryJournalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<JournalFilter>;
};

export type DocumentFilter = {
  general?: InputMaybe<GeneralFilter>;
  acts?: InputMaybe<ActsFilter>;
  journal?: InputMaybe<JournalFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = General | Acts | Journal | Folder;

export type GeneralNav_Links = {
  __typename?: 'GeneralNav_links';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type General = Node & Document & {
  __typename?: 'General';
  seo_title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  nav_links?: Maybe<Array<Maybe<GeneralNav_Links>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type GeneralNav_LinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type GeneralFilter = {
  seo_title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  nav_links?: InputMaybe<GeneralNav_LinksFilter>;
};

export type GeneralConnectionEdges = {
  __typename?: 'GeneralConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<General>;
};

export type GeneralConnection = Connection & {
  __typename?: 'GeneralConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GeneralConnectionEdges>>>;
};

export type ActsCourses = {
  __typename?: 'ActsCourses';
  n?: Maybe<Scalars['String']['output']>;
  numeral?: Maybe<Scalars['String']['output']>;
  time?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  sense?: Maybe<Scalars['String']['output']>;
  line?: Maybe<Scalars['String']['output']>;
  img?: Maybe<Scalars['String']['output']>;
  imgB?: Maybe<Scalars['String']['output']>;
  accent?: Maybe<Scalars['String']['output']>;
  choice?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Acts = Node & Document & {
  __typename?: 'Acts';
  courses?: Maybe<Array<Maybe<ActsCourses>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ActsCoursesFilter = {
  n?: InputMaybe<StringFilter>;
  numeral?: InputMaybe<StringFilter>;
  time?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  sense?: InputMaybe<StringFilter>;
  line?: InputMaybe<StringFilter>;
  img?: InputMaybe<ImageFilter>;
  imgB?: InputMaybe<ImageFilter>;
  accent?: InputMaybe<StringFilter>;
  choice?: InputMaybe<StringFilter>;
};

export type ActsFilter = {
  courses?: InputMaybe<ActsCoursesFilter>;
};

export type ActsConnectionEdges = {
  __typename?: 'ActsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Acts>;
};

export type ActsConnection = Connection & {
  __typename?: 'ActsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ActsConnectionEdges>>>;
};

export type Journal = Node & Document & {
  __typename?: 'Journal';
  title: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['RichText']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type JournalFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  category?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type JournalConnectionEdges = {
  __typename?: 'JournalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Journal>;
};

export type JournalConnection = Connection & {
  __typename?: 'JournalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<JournalConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateGeneral: General;
  createGeneral: General;
  updateActs: Acts;
  createActs: Acts;
  updateJournal: Journal;
  createJournal: Journal;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateGeneralArgs = {
  relativePath: Scalars['String']['input'];
  params: GeneralMutation;
};


export type MutationCreateGeneralArgs = {
  relativePath: Scalars['String']['input'];
  params: GeneralMutation;
};


export type MutationUpdateActsArgs = {
  relativePath: Scalars['String']['input'];
  params: ActsMutation;
};


export type MutationCreateActsArgs = {
  relativePath: Scalars['String']['input'];
  params: ActsMutation;
};


export type MutationUpdateJournalArgs = {
  relativePath: Scalars['String']['input'];
  params: JournalMutation;
};


export type MutationCreateJournalArgs = {
  relativePath: Scalars['String']['input'];
  params: JournalMutation;
};

export type DocumentUpdateMutation = {
  general?: InputMaybe<GeneralMutation>;
  acts?: InputMaybe<ActsMutation>;
  journal?: InputMaybe<JournalMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  general?: InputMaybe<GeneralMutation>;
  acts?: InputMaybe<ActsMutation>;
  journal?: InputMaybe<JournalMutation>;
};

export type GeneralNav_LinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type GeneralMutation = {
  seo_title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  nav_links?: InputMaybe<Array<InputMaybe<GeneralNav_LinksMutation>>>;
};

export type ActsCoursesMutation = {
  n?: InputMaybe<Scalars['String']['input']>;
  numeral?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  sense?: InputMaybe<Scalars['String']['input']>;
  line?: InputMaybe<Scalars['String']['input']>;
  img?: InputMaybe<Scalars['String']['input']>;
  imgB?: InputMaybe<Scalars['String']['input']>;
  accent?: InputMaybe<Scalars['String']['input']>;
  choice?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ActsMutation = {
  courses?: InputMaybe<Array<InputMaybe<ActsCoursesMutation>>>;
};

export type JournalMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['RichText']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type GeneralNav_LinksFilter = {
  label?: StringFilter | null | undefined;
  href?: StringFilter | null | undefined;
};

export type GeneralFilter = {
  seo_title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  nav_links?: GeneralNav_LinksFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type ActsCoursesFilter = {
  n?: StringFilter | null | undefined;
  numeral?: StringFilter | null | undefined;
  time?: StringFilter | null | undefined;
  name?: StringFilter | null | undefined;
  sense?: StringFilter | null | undefined;
  line?: StringFilter | null | undefined;
  img?: ImageFilter | null | undefined;
  imgB?: ImageFilter | null | undefined;
  accent?: StringFilter | null | undefined;
  choice?: StringFilter | null | undefined;
};

export type ActsFilter = {
  courses?: ActsCoursesFilter | null | undefined;
};

export type DatetimeFilter = {
  after?: string | null | undefined;
  before?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type RichTextFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
};

export type JournalFilter = {
  title?: StringFilter | null | undefined;
  date?: DatetimeFilter | null | undefined;
  category?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type GeneralPartsFragment = { __typename: 'General', seo_title: string | null, description: string | null, nav_links: Array<{ __typename: 'GeneralNav_links', label: string | null, href: string | null } | null> | null };

export type ActsPartsFragment = { __typename: 'Acts', courses: Array<{ __typename: 'ActsCourses', n: string | null, numeral: string | null, time: string | null, name: string | null, sense: string | null, line: string | null, img: string | null, imgB: string | null, accent: string | null, choice: Array<string | null> | null } | null> | null };

export type JournalPartsFragment = { __typename: 'Journal', title: string, date: string | null, category: string | null, description: string | null, image: string | null, body: TinaMarkdownContent | null };

export type GeneralQueryVariables = Exact<{
  relativePath: string;
}>;


export type GeneralQuery = { general: { __typename: 'General', id: string, seo_title: string | null, description: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav_links: Array<{ __typename: 'GeneralNav_links', label: string | null, href: string | null } | null> | null } };

export type GeneralConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: GeneralFilter | null | undefined;
}>;


export type GeneralConnectionQuery = { generalConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'General', id: string, seo_title: string | null, description: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav_links: Array<{ __typename: 'GeneralNav_links', label: string | null, href: string | null } | null> | null } | null } | null> | null } };

export type ActsQueryVariables = Exact<{
  relativePath: string;
}>;


export type ActsQuery = { acts: { __typename: 'Acts', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, courses: Array<{ __typename: 'ActsCourses', n: string | null, numeral: string | null, time: string | null, name: string | null, sense: string | null, line: string | null, img: string | null, imgB: string | null, accent: string | null, choice: Array<string | null> | null } | null> | null } };

export type ActsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ActsFilter | null | undefined;
}>;


export type ActsConnectionQuery = { actsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Acts', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, courses: Array<{ __typename: 'ActsCourses', n: string | null, numeral: string | null, time: string | null, name: string | null, sense: string | null, line: string | null, img: string | null, imgB: string | null, accent: string | null, choice: Array<string | null> | null } | null> | null } | null } | null> | null } };

export type JournalQueryVariables = Exact<{
  relativePath: string;
}>;


export type JournalQuery = { journal: { __typename: 'Journal', id: string, title: string, date: string | null, category: string | null, description: string | null, image: string | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type JournalConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: JournalFilter | null | undefined;
}>;


export type JournalConnectionQuery = { journalConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Journal', id: string, title: string, date: string | null, category: string | null, description: string | null, image: string | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const GeneralPartsFragmentDoc = gql`
    fragment GeneralParts on General {
  __typename
  seo_title
  description
  nav_links {
    __typename
    label
    href
  }
}
    `;
export const ActsPartsFragmentDoc = gql`
    fragment ActsParts on Acts {
  __typename
  courses {
    __typename
    n
    numeral
    time
    name
    sense
    line
    img
    imgB
    accent
    choice
  }
}
    `;
export const JournalPartsFragmentDoc = gql`
    fragment JournalParts on Journal {
  __typename
  title
  date
  category
  description
  image
  body
}
    `;
export const GeneralDocument = gql`
    query general($relativePath: String!) {
  general(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GeneralParts
  }
}
    ${GeneralPartsFragmentDoc}`;
export const GeneralConnectionDocument = gql`
    query generalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GeneralFilter) {
  generalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GeneralParts
      }
    }
  }
}
    ${GeneralPartsFragmentDoc}`;
export const ActsDocument = gql`
    query acts($relativePath: String!) {
  acts(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ActsParts
  }
}
    ${ActsPartsFragmentDoc}`;
export const ActsConnectionDocument = gql`
    query actsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ActsFilter) {
  actsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ActsParts
      }
    }
  }
}
    ${ActsPartsFragmentDoc}`;
export const JournalDocument = gql`
    query journal($relativePath: String!) {
  journal(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...JournalParts
  }
}
    ${JournalPartsFragmentDoc}`;
export const JournalConnectionDocument = gql`
    query journalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: JournalFilter) {
  journalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...JournalParts
      }
    }
  }
}
    ${JournalPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      general(variables: GeneralQueryVariables, options?: C): Promise<{data: GeneralQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GeneralQueryVariables, query: string}> {
        return requester<{data: GeneralQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GeneralQueryVariables, query: string}, GeneralQueryVariables>(GeneralDocument, variables, options);
      },
    generalConnection(variables?: GeneralConnectionQueryVariables, options?: C): Promise<{data: GeneralConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GeneralConnectionQueryVariables, query: string}> {
        return requester<{data: GeneralConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GeneralConnectionQueryVariables, query: string}, GeneralConnectionQueryVariables>(GeneralConnectionDocument, variables, options);
      },
    acts(variables: ActsQueryVariables, options?: C): Promise<{data: ActsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActsQueryVariables, query: string}> {
        return requester<{data: ActsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActsQueryVariables, query: string}, ActsQueryVariables>(ActsDocument, variables, options);
      },
    actsConnection(variables?: ActsConnectionQueryVariables, options?: C): Promise<{data: ActsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActsConnectionQueryVariables, query: string}> {
        return requester<{data: ActsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ActsConnectionQueryVariables, query: string}, ActsConnectionQueryVariables>(ActsConnectionDocument, variables, options);
      },
    journal(variables: JournalQueryVariables, options?: C): Promise<{data: JournalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalQueryVariables, query: string}> {
        return requester<{data: JournalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalQueryVariables, query: string}, JournalQueryVariables>(JournalDocument, variables, options);
      },
    journalConnection(variables?: JournalConnectionQueryVariables, options?: C): Promise<{data: JournalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalConnectionQueryVariables, query: string}> {
        return requester<{data: JournalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalConnectionQueryVariables, query: string}, JournalConnectionQueryVariables>(JournalConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/3.0/content/f025514a-f4b6-489a-89d2-906074df8f69/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  